CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE users (id UUID PRIMARY KEY,email TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE workspaces (id UUID PRIMARY KEY,name TEXT NOT NULL,owner_id UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE memberships (workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL CHECK (role IN ('owner','lead','member')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY (workspace_id,user_id));
CREATE TABLE board_items (id UUID PRIMARY KEY,workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE,author_id UUID NOT NULL REFERENCES users(id),kind TEXT NOT NULL CHECK (kind IN ('task','announcement','question','schedule')),title TEXT NOT NULL,body TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'todo',due_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE publications (event_id UUID PRIMARY KEY,source_item_id UUID NOT NULL,workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,target_item_id UUID REFERENCES board_items(id),actor_id UUID NOT NULL REFERENCES users(id),state TEXT NOT NULL CHECK (state IN ('queued','published','failed')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),published_at TIMESTAMPTZ);
CREATE TABLE activity_events (id UUID PRIMARY KEY,workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE,actor_id UUID NOT NULL REFERENCES users(id),event_type TEXT NOT NULL,subject_id UUID,detail JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE rag_sources (id UUID PRIMARY KEY,owner_id UUID NOT NULL REFERENCES users(id),title TEXT NOT NULL,origin_uri TEXT,checksum TEXT NOT NULL,privacy_scope TEXT NOT NULL CHECK (privacy_scope IN ('personal','workspace')),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE rag_chunks (id UUID PRIMARY KEY,source_id UUID NOT NULL REFERENCES rag_sources(id) ON DELETE CASCADE,ordinal INTEGER NOT NULL,content TEXT NOT NULL,embedding vector(1536),UNIQUE(source_id,ordinal));
