import { FormEvent, useEffect, useMemo, useState } from 'react';
import { BoardState, WorkItem, WorkKind, WorkScope, kindLabel, statusLabel } from './domain';
import { loadBoard, makeId, saveBoard } from './localBoard';

type View = 'today' | 'personal' | 'shared' | 'announcements' | 'questions' | 'sync';
type Theme = 'dark' | 'light';
const currentUser = '김해경';
const nav: { id: View; label: string; group: string }[] = [
  { id: 'today', label: '오늘', group: '업무' }, { id: 'personal', label: '개인 보드', group: '업무' },
  { id: 'shared', label: '공유 보드', group: '함께 보기' }, { id: 'announcements', label: '공지 확인', group: '함께 보기' }, { id: 'questions', label: '질문과 결정', group: '함께 보기' }, { id: 'sync', label: '동기화', group: '연결' }
];
const viewCopy: Record<View, [string, string]> = {
  today: ['오늘 필요한 일만 봅니다.', '개인 일과 공유된 마감을 한 화면에서 확인합니다.'], personal: ['개인 보드에서 먼저 정리합니다.', '이 공간의 항목은 이 브라우저에만 저장됩니다.'], shared: ['팀이 함께 볼 일을 확인합니다.', '개인 항목을 공유하면 동기화 대기열에 기록됩니다.'], announcements: ['공지 확인 기록을 남깁니다.', '읽음 처리는 팀 서버에 보낼 수 있는 별도 이벤트입니다.'], questions: ['질문을 남기고 결정을 이어갑니다.', '답이 필요한 일을 업무와 분리해 놓치지 않게 합니다.'], sync: ['공유 이벤트를 관리합니다.', '개인 원본은 보내지 않고, 공유를 선택한 항목만 전송합니다.']
};

export function UniversalBoard() {
  const [board, setBoard] = useState<BoardState>(loadBoard);
  const [view, setView] = useState<View>('today'); const [theme, setTheme] = useState<Theme>('dark');
  const [selectedId, setSelectedId] = useState('personal-model'); const [composerOpen, setComposerOpen] = useState(false); const [notice, setNotice] = useState('');
  useEffect(() => saveBoard(board), [board]);
  const selected = board.items.find((item) => item.id === selectedId) ?? board.items[0];
  const unreadCount = board.items.filter((item) => item.kind === 'announcement' && !item.readBy.includes(currentUser)).length;
  const visible = useMemo(() => filterItems(board.items, view), [board.items, view]);
  const dueToday = board.items.filter((item) => item.due === '오늘' && item.status !== 'done').length;
  const queue = (itemId: string, type: 'publication' | 'item_update' | 'read_receipt') => ({ eventId: makeId(), itemId, type, occurredAt: new Date().toISOString(), state: 'pending' as const });
  function changeItem(item: WorkItem, change: Partial<WorkItem>, type: 'item_update' | 'read_receipt' = 'item_update') { setBoard((current) => ({ items: current.items.map((entry) => entry.id === item.id ? { ...entry, ...change, updatedAt: new Date().toISOString() } : entry), outbox: [...current.outbox, queue(item.id, type)] })); }
  function publish(item: WorkItem) { if (item.scope === 'shared') return setNotice('이미 공유 보드에 있는 항목입니다.'); setBoard((current) => ({ items: current.items.map((entry) => entry.id === item.id ? { ...entry, scope: 'shared', workspace: '운영팀', updatedAt: new Date().toISOString() } : entry), outbox: [...current.outbox, queue(item.id, 'publication')] })); setNotice('공유 항목으로 전환했고, 전송 대기열에 넣었습니다.'); }
  function markRead(item: WorkItem) { if (item.readBy.includes(currentUser)) return; changeItem(item, { readBy: [...item.readBy, currentUser] }, 'read_receipt'); setNotice('공지 읽음 기록을 전송 대기열에 넣었습니다.'); }
  function addItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const title = String(form.get('title') ?? '').trim(); if (!title) return; const kind = String(form.get('kind') ?? 'task') as WorkKind; const scope = String(form.get('scope') ?? 'personal') as WorkScope; const updatedAt = new Date().toISOString(); const item: WorkItem = { id: makeId(), title, kind, scope, workspace: scope === 'personal' ? '나의 보드' : '운영팀', due: String(form.get('due') ?? '마감 미정'), status: 'todo', priority: '보통', body: String(form.get('body') ?? ''), updatedAt, readBy: [] }; setBoard((current) => ({ items: [item, ...current.items], outbox: scope === 'shared' ? [...current.outbox, queue(item.id, 'publication')] : current.outbox })); setSelectedId(item.id); setComposerOpen(false); setNotice(scope === 'shared' ? '공유 항목을 만들고 전송 대기열에 넣었습니다.' : '개인 보드에 업무를 추가했습니다.'); }
  async function sendOutbox() { const endpoint = import.meta.env.VITE_SYNC_API_BASE as string | undefined; const pending = board.outbox.filter((event) => event.state === 'pending'); if (!pending.length) return setNotice('보낼 공유 이벤트가 없습니다.'); if (!endpoint) return setNotice('아직 서버 주소가 없습니다. .env에 VITE_SYNC_API_BASE를 넣으면 전송할 수 있습니다.'); try { const response = await fetch(`${endpoint.replace(/\/$/, '')}/v1/sync/events`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ actorName: currentUser, events: pending.map((event) => ({ ...event, item: board.items.find((item) => item.id === event.itemId) })) }) }); if (!response.ok) throw new Error(String(response.status)); setBoard((current) => ({ ...current, outbox: current.outbox.map((event) => pending.some((entry) => entry.eventId === event.eventId) ? { ...event, state: 'sent' } : event) })); setNotice(`${pending.length}개 공유 이벤트를 보냈습니다.`); } catch { setBoard((current) => ({ ...current, outbox: current.outbox.map((event) => pending.some((entry) => entry.eventId === event.eventId) ? { ...event, state: 'failed' } : event) })); setNotice('전송하지 못했습니다. 서버 주소와 권한을 확인해 주세요.'); } }
  function exportOutbox() { const content = JSON.stringify({ exportedAt: new Date().toISOString(), events: board.outbox, items: board.items.filter((item) => item.scope === 'shared') }, null, 2); const url = URL.createObjectURL(new Blob([content], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'work-board-sync-events.json'; link.click(); URL.revokeObjectURL(url); setNotice('공유 항목과 전송 대기열을 JSON 파일로 내보냈습니다.'); }
  return <div className={`universal-board ${theme}`}>
    <aside className="board-nav"><div className="board-brand"><span className="brand-corner" aria-hidden="true" /><span>일의 자리</span></div>{['업무', '함께 보기', '연결'].map((group) => <div className="nav-group" key={group}><p>{group}</p>{nav.filter((entry) => entry.group === group).map((entry) => <button key={entry.id} className={view === entry.id ? 'nav-active' : ''} onClick={() => setView(entry.id)}>{entry.label}{entry.id === 'announcements' && unreadCount > 0 ? <b>{unreadCount}</b> : null}</button>)}</div>)}<div className="device-note"><span>이 기기</span><strong>개인 원본 보관</strong><small>공유 선택 항목만 전송</small></div></aside>
    <main className="board-workspace"><header className="board-header"><div><p className="eyebrow">LOCAL-FIRST WORK BOARD</p><h1>{viewCopy[view][0]}</h1><p>{viewCopy[view][1]}</p></div><div className="header-actions"><button className="quiet-button" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? '라이트 화면' : '다크 화면'}</button><button className="primary-button" onClick={() => setComposerOpen(true)}>새 업무</button></div></header>{notice && <div className="notice" role="status">{notice}<button aria-label="안내 닫기" onClick={() => setNotice('')}>×</button></div>}{view === 'sync' ? <SyncView board={board} onSend={sendOutbox} onExport={exportOutbox} /> : <><section className="focus-strip"><div><span>오늘 마감</span><strong>{dueToday}개</strong></div><div><span>읽지 않은 공지</span><strong>{unreadCount}개</strong></div><div className="meaning-vector"><svg viewBox="0 0 160 34" aria-label="개인에서 공유로 이어지는 흐름" role="img"><path d="M8 17H142" stroke="currentColor" strokeWidth="4" /><path d="m133 8 10 9-10 9" fill="none" stroke="currentColor" strokeWidth="4" /></svg><span>개인 정리 → 필요한 것만 공유</span></div></section><section className="board-list" aria-label="업무 목록"><div className="list-heading"><div><p className="eyebrow">{nav.find((entry) => entry.id === view)?.label}</p><h2>{visible.length}개 항목</h2></div><span>{view === 'personal' ? '로컬 저장' : '공유 항목 포함'}</span></div><div className="list-columns"><span>종류</span><span>제목</span><span>공간</span><span>마감</span><span>상태</span></div>{visible.map((item) => <button className={`work-row ${selected?.id === item.id ? 'is-selected' : ''}`} key={item.id} onClick={() => setSelectedId(item.id)}><span className={`kind-mark kind-${item.kind}`}>{kindLabel[item.kind]}</span><strong>{item.title}</strong><span>{item.workspace}</span><span>{item.due}</span><span className={`status status-${item.status}`}>{statusLabel[item.status]}</span></button>)}</section></>}</main>
    <aside className="board-inspector">{selected && <><div className="inspector-label"><span>{kindLabel[selected.kind]}</span><span>{selected.scope === 'personal' ? '개인' : '공유'}</span></div><h2>{selected.title}</h2><p className="inspector-body">{selected.body || '추가 메모가 없습니다.'}</p><dl><div><dt>공간</dt><dd>{selected.workspace}</dd></div><div><dt>마감</dt><dd>{selected.due}</dd></div></dl><div className="inspector-actions">{selected.kind === 'announcement' && <button className="primary-button" onClick={() => markRead(selected)}>{selected.readBy.includes(currentUser) ? '읽음 기록됨' : '읽음으로 기록'}</button>}{selected.kind === 'task' && <button className="quiet-button" onClick={() => changeItem(selected, { status: selected.status === 'done' ? 'todo' : 'done' })}>{selected.status === 'done' ? '다시 열기' : '완료 처리'}</button>}{selected.scope === 'personal' && <button className="primary-button" onClick={() => publish(selected)}>공유하기</button>}</div><section className="history"><p className="eyebrow">최근 이력</p><p>{selected.scope === 'personal' ? '이 기기에 개인 항목으로 저장됨' : '팀에 공유할 수 있는 항목으로 분류됨'}</p>{selected.kind === 'announcement' && <p>{selected.readBy.length}명이 공지를 확인함</p>}</section></>}</aside>
    {composerOpen && <Composer onClose={() => setComposerOpen(false)} onSubmit={addItem} />}
  </div>;
}
function filterItems(items: WorkItem[], view: View) { if (view === 'today') return items.filter((item) => item.due === '오늘' || item.kind === 'announcement'); if (view === 'personal') return items.filter((item) => item.scope === 'personal'); if (view === 'shared') return items.filter((item) => item.scope === 'shared'); if (view === 'announcements') return items.filter((item) => item.kind === 'announcement'); if (view === 'questions') return items.filter((item) => item.kind === 'question'); return []; }
function Composer({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="composer-backdrop"><form className="composer" onSubmit={onSubmit}><div><p className="eyebrow">새 항목</p><h2>업무를 기록합니다.</h2></div><label>업무 제목<input name="title" autoFocus placeholder="예: 고객 인터뷰 일정 확정" required /></label><label>종류<select name="kind" defaultValue="task"><option value="task">업무</option><option value="announcement">공지</option><option value="question">질문</option><option value="schedule">일정</option></select></label><label>저장 위치<select name="scope" defaultValue="personal"><option value="personal">개인 보드</option><option value="shared">공유 보드</option></select></label><label>마감<input name="due" placeholder="예: 9월 25일 또는 오늘" /></label><label>메모<textarea name="body" placeholder="이 일이 왜 필요한지 적어 둡니다." /></label><div className="composer-actions"><button type="button" className="quiet-button" onClick={onClose}>취소</button><button type="submit" className="primary-button">기록하기</button></div></form></div>; }
function SyncView({ board, onSend, onExport }: { board: BoardState; onSend: () => void; onExport: () => void }) { const pending = board.outbox.filter((entry) => entry.state === 'pending'); return <section className="sync-view"><p className="eyebrow">SHARED EVENT OUTBOX</p><h2>공유만 전송합니다.</h2><p>개인 메모와 원본은 이 기기에 남습니다. 선택한 공유 항목, 공지 읽음, 공유 항목 수정만 동기화 이벤트로 보냅니다.</p><div className="sync-stat"><strong>{pending.length}</strong><span>전송 대기</span></div><div className="sync-actions"><button className="primary-button" onClick={onSend}>대기 항목 보내기</button><button className="quiet-button" onClick={onExport}>JSON으로 내보내기</button></div><div className="event-log">{board.outbox.length ? board.outbox.map((event) => <p key={event.eventId}><span>{event.type}</span><span>{event.state === 'pending' ? '전송 대기' : event.state === 'sent' ? '전송됨' : '재시도 필요'}</span></p>) : <p>아직 공유 이벤트가 없습니다.</p>}</div></section>; }
